apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: depot
  labels:
    app: flask-front
  name: flask-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-front
  template:
    metadata:
      labels:
        app: flask-front
    spec:
      containers:
      - name: flask-front
        image: 192.168.1.14:9000/flask-front:1.0.0
        env:
        - name: AUTH
          value: "go-auth-service:8080/login"
        - name: CATALOG
          value: "go-catalog-service:8080"
        - name: SECRET_KEY
          value: "123"
        ports:
        - containerPort: 5000

