apiVersion: v1
kind: Service
metadata:
  namespace: depot
  name: flask-front-service
  labels:
    app: flask-front-service
spec:
  selector:
    app: flask-front-service
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: ClusterIP
