openapi: 3.0.0
info:
  title: Авторизация Depot
  description: Авторизация и добавление пользователей Depot
  version: 1.0.0
servers:
  - url: http://localhost:18080
    description: Local podman server
paths:
  /add:
    post:
      summary: Добавить пользователя
      description: Возвращает объект User
      requestBody:
        description: Данные пользователя указанные при регестрации регистрации
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - password
              properties:
                name:
                  type: string
                  description: Уникальное имя пользователя
                email:
                  type: string
                  description: Уникальный адрес электронной почты
                password:
                  type: string
                  description: Пароль длиной не менее 8 символов
      responses:
        '201':
          description: Пользователь добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Ошибка на стороне сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /login:
    post:
      summary: Авторизация пользователя
      description: Возвращает jwt токен
      requestBody:
        description: Для авторизации необходимы имя пользователя и пароль
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - password
              properties:
                name:
                  type: string
                  description: Уникальное имя пользователя
                password:
                  type: string
                  description: Пароль
      responses:
        '200':
          description: Авторизация выполнена 
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT токен
        '400':
          description: Ошибка авторизации, неперные олгин или пароль
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор пользователя
        name:
          type: string
          description: Имя пользователя
        email:
          type: string
          description: Электронная почта пользователя
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Текст ошибки
