server:
  host: 0.0.0.0 
  port: 8080

db:
  type: postgres
  
  postgres:
    host: postgres
    port: 5432
    user: postgres
    password: postgres
    dbname: postgres
    sslmode: disable

  sqlite:
    path: app.db
