openapi: 3.0.0
info:
  title: Учебный процесс
  discription: Информация о специальностях, группах, предметах, студентах, преподавателях и аудиториях
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: podman server
